class GlobalExerciseDef {
  final String name;
  final String group;

  const GlobalExerciseDef(this.name, this.group);
}

const kAllDefaultExercises = [
  // Chest
  GlobalExerciseDef('Barbell Bench Press', 'chest'),
  GlobalExerciseDef('Incline Barbell Bench Press', 'chest'),
  GlobalExerciseDef('Decline Barbell Bench Press', 'chest'),
  GlobalExerciseDef('Dumbbell Bench Press', 'chest'),
  GlobalExerciseDef('Incline Dumbbell Bench Press', 'chest'),
  GlobalExerciseDef('Decline Dumbbell Bench Press', 'chest'),
  GlobalExerciseDef('Dumbbell Flyes', 'chest'),
  GlobalExerciseDef('Incline Dumbbell Flyes', 'chest'),
  GlobalExerciseDef('Cable Flyes (High)', 'chest'),
  GlobalExerciseDef('Cable Flyes (Mid)', 'chest'),
  GlobalExerciseDef('Cable Flyes (Low)', 'chest'),
  GlobalExerciseDef('Cable Crossovers', 'chest'),
  GlobalExerciseDef('Pec Deck Machine', 'chest'),
  GlobalExerciseDef('Machine Chest Press', 'chest'),
  GlobalExerciseDef('Smith Machine Bench Press', 'chest'),
  GlobalExerciseDef('Push-ups', 'chest'),
  GlobalExerciseDef('Incline Push-ups', 'chest'),
  GlobalExerciseDef('Decline Push-ups', 'chest'),
  GlobalExerciseDef('Diamond Push-ups', 'chest'),
  GlobalExerciseDef('Wide-grip Push-ups', 'chest'),
  GlobalExerciseDef('Archer Push-ups', 'chest'),
  GlobalExerciseDef('Plyometric Push-ups', 'chest'),
  GlobalExerciseDef('Deficit Push-ups', 'chest'),
  GlobalExerciseDef('Ring Push-ups', 'chest'),
  GlobalExerciseDef('Dips (Chest-focused)', 'chest'),
  GlobalExerciseDef('Svend Press', 'chest'),
  GlobalExerciseDef('Landmine Press', 'chest'),
  GlobalExerciseDef('Floor Press', 'chest'),
  GlobalExerciseDef('Guillotine Press', 'chest'),
  GlobalExerciseDef('Pin Press', 'chest'),
  GlobalExerciseDef('Hex Press', 'chest'),
  GlobalExerciseDef('Single-arm Dumbbell Press', 'chest'),
  GlobalExerciseDef('Around-the-worlds', 'chest'),

  // Shoulders
  GlobalExerciseDef('Overhead Barbell Press (Standing)', 'shoulders'),
  GlobalExerciseDef('Seated Barbell Press', 'shoulders'),
  GlobalExerciseDef('Push Press', 'shoulders'),
  GlobalExerciseDef('Push Jerk', 'shoulders'),
  GlobalExerciseDef('Dumbbell Shoulder Press', 'shoulders'),
  GlobalExerciseDef('Arnold Press', 'shoulders'),
  GlobalExerciseDef('Single-arm Dumbbell Press', 'shoulders'),
  GlobalExerciseDef('Landmine Press', 'shoulders'),
  GlobalExerciseDef('Z-press', 'shoulders'),
  GlobalExerciseDef('Behind-the-neck Press', 'shoulders'),
  GlobalExerciseDef('Machine Shoulder Press', 'shoulders'),
  GlobalExerciseDef('Smith Machine Press', 'shoulders'),
  GlobalExerciseDef('Lateral Raises (Dumbbell)', 'shoulders'),
  GlobalExerciseDef('Cable Lateral Raises', 'shoulders'),
  GlobalExerciseDef('Machine Lateral Raises', 'shoulders'),
  GlobalExerciseDef('Leaning Lateral Raises', 'shoulders'),
  GlobalExerciseDef('Lying Side Lateral Raises', 'shoulders'),
  GlobalExerciseDef('Front Raises (Dumbbell)', 'shoulders'),
  GlobalExerciseDef('Front Raises (Barbell)', 'shoulders'),
  GlobalExerciseDef('Front Raises (Plate)', 'shoulders'),
  GlobalExerciseDef('Front Raises (Cable)', 'shoulders'),
  GlobalExerciseDef('Rear Delt Flyes (Dumbbell)', 'shoulders'),
  GlobalExerciseDef('Bent-over Rear Delt Raises', 'shoulders'),
  GlobalExerciseDef('Reverse Pec Deck', 'shoulders'),
  GlobalExerciseDef('Face Pulls', 'shoulders'),
  GlobalExerciseDef('Cable Rear Delt Rows', 'shoulders'),
  GlobalExerciseDef('High Pulls', 'shoulders'),
  GlobalExerciseDef('Upright Rows (Barbell)', 'shoulders'),
  GlobalExerciseDef('Upright Rows (Dumbbell)', 'shoulders'),
  GlobalExerciseDef('Upright Rows (Cable)', 'shoulders'),
  GlobalExerciseDef('Cuban Press', 'shoulders'),
  GlobalExerciseDef('Scaption Raises', 'shoulders'),
  GlobalExerciseDef('Handstand Push-ups', 'shoulders'),
  GlobalExerciseDef('Pike Push-ups', 'shoulders'),

  // Back
  GlobalExerciseDef('Deadlift', 'back'),
  GlobalExerciseDef('Conventional Deadlift', 'back'),
  GlobalExerciseDef('Sumo Deadlift', 'back'),
  GlobalExerciseDef('Romanian Deadlift', 'back'),
  GlobalExerciseDef('Trap Bar Deadlift', 'back'),
  GlobalExerciseDef('Deficit Deadlift', 'back'),
  GlobalExerciseDef('Rack Pulls', 'back'),
  GlobalExerciseDef('Pull-ups', 'back'),
  GlobalExerciseDef('Chin-ups', 'back'),
  GlobalExerciseDef('Neutral-grip Pull-ups', 'back'),
  GlobalExerciseDef('Weighted Pull-ups', 'back'),
  GlobalExerciseDef('Wide-grip Pull-ups', 'back'),
  GlobalExerciseDef('Lat Pulldowns', 'back'),
  GlobalExerciseDef('Close-grip Pulldowns', 'back'),
  GlobalExerciseDef('Reverse-grip Pulldowns', 'back'),
  GlobalExerciseDef('Single-arm Pulldowns', 'back'),
  GlobalExerciseDef('Straight-arm Pulldowns', 'back'),
  GlobalExerciseDef('Bent-over Barbell Rows', 'back'),
  GlobalExerciseDef('Pendlay Rows', 'back'),
  GlobalExerciseDef('Yates Rows', 'back'),
  GlobalExerciseDef('Dumbbell Rows', 'back'),
  GlobalExerciseDef('Single-arm Dumbbell Rows', 'back'),
  GlobalExerciseDef('Chest-supported Rows', 'back'),
  GlobalExerciseDef('T-bar Rows', 'back'),
  GlobalExerciseDef('Seal Rows', 'back'),
  GlobalExerciseDef('Seated Cable Rows', 'back'),
  GlobalExerciseDef('Wide-grip Cable Rows', 'back'),
  GlobalExerciseDef('Machine Rows', 'back'),
  GlobalExerciseDef('Meadows Rows', 'back'),
  GlobalExerciseDef('Inverted Rows', 'back'),
  GlobalExerciseDef('Kroc Rows', 'back'),
  GlobalExerciseDef('Shrugs (Barbell)', 'back'),
  GlobalExerciseDef('Shrugs (Dumbbell)', 'back'),
  GlobalExerciseDef('Shrugs (Trap Bar)', 'back'),
  GlobalExerciseDef('Shrugs (Cable)', 'back'),
  GlobalExerciseDef('Good Mornings', 'back'),
  GlobalExerciseDef('Back Extensions', 'back'),
  GlobalExerciseDef('Reverse Hyperextensions', 'back'),
  GlobalExerciseDef('Supermans', 'back'),
  GlobalExerciseDef('Renegade Rows', 'back'),
  GlobalExerciseDef('Pullovers (Dumbbell)', 'back'),
  GlobalExerciseDef('Pullovers (Cable)', 'back'),

  // Biceps
  GlobalExerciseDef('Barbell Curls', 'biceps'),
  GlobalExerciseDef('EZ-bar Curls', 'biceps'),
  GlobalExerciseDef('Dumbbell Curls', 'biceps'),
  GlobalExerciseDef('Alternating Dumbbell Curls', 'biceps'),
  GlobalExerciseDef('Hammer Curls', 'biceps'),
  GlobalExerciseDef('Cross-body Hammer Curls', 'biceps'),
  GlobalExerciseDef('Incline Dumbbell Curls', 'biceps'),
  GlobalExerciseDef('Preacher Curls (Barbell)', 'biceps'),
  GlobalExerciseDef('Preacher Curls (Dumbbell)', 'biceps'),
  GlobalExerciseDef('Preacher Curls (Machine)', 'biceps'),
  GlobalExerciseDef('Scott Curls', 'biceps'),
  GlobalExerciseDef('Spider Curls', 'biceps'),
  GlobalExerciseDef('Concentration Curls', 'biceps'),
  GlobalExerciseDef('Cable Curls', 'biceps'),
  GlobalExerciseDef('Cable Rope Hammer Curls', 'biceps'),
  GlobalExerciseDef('High Cable Curls', 'biceps'),
  GlobalExerciseDef('Drag Curls', 'biceps'),
  GlobalExerciseDef('Zottman Curls', 'biceps'),
  GlobalExerciseDef('21s', 'biceps'),
  GlobalExerciseDef('Reverse-grip Barbell Curls', 'biceps'),
  GlobalExerciseDef('Chin-ups (Biceps Focus)', 'biceps'),
  GlobalExerciseDef('Bodyweight Curls (Rings)', 'biceps'),
  GlobalExerciseDef('Waiter Curls', 'biceps'),
  GlobalExerciseDef('Behind-the-back Cable Curls', 'biceps'),

  // Triceps
  GlobalExerciseDef('Close-grip Bench Press', 'triceps'),
  GlobalExerciseDef('JM Press', 'triceps'),
  GlobalExerciseDef('Skull Crushers (EZ-bar)', 'triceps'),
  GlobalExerciseDef('Skull Crushers (Dumbbell)', 'triceps'),
  GlobalExerciseDef('Skull Crushers (Barbell)', 'triceps'),
  GlobalExerciseDef('French Press', 'triceps'),
  GlobalExerciseDef('Overhead Triceps Extensions (Dumbbell)', 'triceps'),
  GlobalExerciseDef('Overhead Triceps Extensions (Cable)', 'triceps'),
  GlobalExerciseDef('Overhead Triceps Extensions (Barbell)', 'triceps'),
  GlobalExerciseDef('Single-arm Overhead Extensions', 'triceps'),
  GlobalExerciseDef('Triceps Pushdowns (Rope)', 'triceps'),
  GlobalExerciseDef('Triceps Pushdowns (V-bar)', 'triceps'),
  GlobalExerciseDef('Triceps Pushdowns (Straight Bar)', 'triceps'),
  GlobalExerciseDef('Triceps Pushdowns (Reverse-grip)', 'triceps'),
  GlobalExerciseDef('Cable Kickbacks', 'triceps'),
  GlobalExerciseDef('Dumbbell Kickbacks', 'triceps'),
  GlobalExerciseDef('Dips (Triceps-focused)', 'triceps'),
  GlobalExerciseDef('Bench Dips', 'triceps'),
  GlobalExerciseDef('Tate Press', 'triceps'),
  GlobalExerciseDef('California Press', 'triceps'),
  GlobalExerciseDef('Board Press', 'triceps'),
  GlobalExerciseDef('Single-arm Cable Pushdowns', 'triceps'),
  GlobalExerciseDef('Cross-body Cable Extensions', 'triceps'),

  // Forearms
  GlobalExerciseDef('Wrist Curls (Barbell)', 'forearms'),
  GlobalExerciseDef('Wrist Curls (Dumbbell)', 'forearms'),
  GlobalExerciseDef('Wrist Curls (Cable)', 'forearms'),
  GlobalExerciseDef('Reverse Wrist Curls', 'forearms'),
  GlobalExerciseDef('Behind-the-back Wrist Curls', 'forearms'),
  GlobalExerciseDef('Reverse Curls (Barbell)', 'forearms'),
  GlobalExerciseDef('Reverse Curls (EZ-bar)', 'forearms'),
  GlobalExerciseDef('Reverse Curls (Cable)', 'forearms'),
  GlobalExerciseDef('Farmer\'s Walks', 'forearms'),
  GlobalExerciseDef('Suitcase Carries', 'forearms'),
  GlobalExerciseDef('Dead Hangs', 'forearms'),
  GlobalExerciseDef('Towel Pull-ups', 'forearms'),
  GlobalExerciseDef('Plate Pinches', 'forearms'),
  GlobalExerciseDef('Gripper Work', 'forearms'),
  GlobalExerciseDef('Wrist Roller', 'forearms'),
  GlobalExerciseDef('Rice Bucket Training', 'forearms'),

  // Quads
  GlobalExerciseDef('Back Squat', 'quads'),
  GlobalExerciseDef('Front Squat', 'quads'),
  GlobalExerciseDef('High-bar Squat', 'quads'),
  GlobalExerciseDef('Low-bar Squat', 'quads'),
  GlobalExerciseDef('Box Squat', 'quads'),
  GlobalExerciseDef('Pause Squat', 'quads'),
  GlobalExerciseDef('Smith Machine Squat', 'quads'),
  GlobalExerciseDef('Hack Squat', 'quads'),
  GlobalExerciseDef('Bulgarian Split Squat', 'quads'),
  GlobalExerciseDef('Split Squat', 'quads'),
  GlobalExerciseDef('Walking Lunges', 'quads'),
  GlobalExerciseDef('Reverse Lunges', 'quads'),
  GlobalExerciseDef('Forward Lunges', 'quads'),
  GlobalExerciseDef('Lateral Lunges', 'quads'),
  GlobalExerciseDef('Curtsy Lunges', 'quads'),
  GlobalExerciseDef('Step-ups', 'quads'),
  GlobalExerciseDef('Leg Press', 'quads'),
  GlobalExerciseDef('Sissy Squats', 'quads'),
  GlobalExerciseDef('Goblet Squat', 'quads'),
  GlobalExerciseDef('Zercher Squat', 'quads'),
  GlobalExerciseDef('Overhead Squat', 'quads'),
  GlobalExerciseDef('Leg Extensions', 'quads'),
  GlobalExerciseDef('Single-leg Leg Extensions', 'quads'),
  GlobalExerciseDef('Cyclist Squat', 'quads'),
  GlobalExerciseDef('Pistol Squat', 'quads'),
  GlobalExerciseDef('Spanish Squat', 'quads'),
  GlobalExerciseDef('Wall Sit', 'quads'),
  GlobalExerciseDef('Jump Squats', 'quads'),

  // Hamstrings
  GlobalExerciseDef('Romanian Deadlift', 'hamstrings'),
  GlobalExerciseDef('Stiff-leg Deadlift', 'hamstrings'),
  GlobalExerciseDef('Single-leg Romanian Deadlift', 'hamstrings'),
  GlobalExerciseDef('Lying Leg Curls', 'hamstrings'),
  GlobalExerciseDef('Seated Leg Curls', 'hamstrings'),
  GlobalExerciseDef('Standing Leg Curls', 'hamstrings'),
  GlobalExerciseDef('Nordic Hamstring Curls', 'hamstrings'),
  GlobalExerciseDef('Glute-ham Raises', 'hamstrings'),
  GlobalExerciseDef('Kettlebell Swings', 'hamstrings'),
  GlobalExerciseDef('Cable Pull-throughs', 'hamstrings'),
  GlobalExerciseDef('Razor Curls', 'hamstrings'),
  GlobalExerciseDef('Banded Leg Curls', 'hamstrings'),

  // Glutes
  GlobalExerciseDef('Hip Thrust (Barbell)', 'glutes'),
  GlobalExerciseDef('Hip Thrust (Machine)', 'glutes'),
  GlobalExerciseDef('Hip Thrust (Single-leg)', 'glutes'),
  GlobalExerciseDef('Glute Bridge', 'glutes'),
  GlobalExerciseDef('B-stance Hip Thrust', 'glutes'),
  GlobalExerciseDef('Frog Pumps', 'glutes'),
  GlobalExerciseDef('Kickbacks (Cable)', 'glutes'),
  GlobalExerciseDef('Kickbacks (Machine)', 'glutes'),
  GlobalExerciseDef('Kickbacks (Banded)', 'glutes'),
  GlobalExerciseDef('Donkey Kicks', 'glutes'),
  GlobalExerciseDef('Fire Hydrants', 'glutes'),
  GlobalExerciseDef('Hip Abduction Machine', 'glutes'),
  GlobalExerciseDef('Banded Clamshells', 'glutes'),
  GlobalExerciseDef('Banded Lateral Walks', 'glutes'),
  GlobalExerciseDef('Monster Walks', 'glutes'),

  // Abs
  GlobalExerciseDef('Crunches', 'abs'),
  GlobalExerciseDef('Sit-ups', 'abs'),
  GlobalExerciseDef('Decline Sit-ups', 'abs'),
  GlobalExerciseDef('Bicycle Crunches', 'abs'),
  GlobalExerciseDef('Reverse Crunches', 'abs'),
  GlobalExerciseDef('Cable Crunches', 'abs'),
  GlobalExerciseDef('Hanging Leg Raises', 'abs'),
  GlobalExerciseDef('Hanging Knee Raises', 'abs'),
  GlobalExerciseDef('Toes-to-bar', 'abs'),
  GlobalExerciseDef('Lying Leg Raises', 'abs'),
  GlobalExerciseDef('V-ups', 'abs'),
  GlobalExerciseDef('Jackknife Sit-ups', 'abs'),
  GlobalExerciseDef('Dragon Flags', 'abs'),
  GlobalExerciseDef('Ab Wheel Rollouts', 'abs'),
  GlobalExerciseDef('Plank', 'abs'),
  GlobalExerciseDef('Side Plank', 'abs'),
  GlobalExerciseDef('Hollow Body Holds', 'abs'),
  GlobalExerciseDef('Dead Bugs', 'abs'),
  GlobalExerciseDef('Russian Twists', 'abs'),
  GlobalExerciseDef('Woodchoppers (Cable)', 'abs'),
  GlobalExerciseDef('Pallof Press', 'abs'),
  GlobalExerciseDef('Landmine Rotations', 'abs'),

  // Calves
  GlobalExerciseDef('Standing Calf Raises (Machine)', 'calves'),
  GlobalExerciseDef('Standing Calf Raises (Barbell)', 'calves'),
  GlobalExerciseDef('Standing Calf Raises (Dumbbell)', 'calves'),
  GlobalExerciseDef('Seated Calf Raises', 'calves'),
  GlobalExerciseDef('Donkey Calf Raises', 'calves'),
  GlobalExerciseDef('Leg Press Calf Raises', 'calves'),
  GlobalExerciseDef('Single-leg Calf Raises', 'calves'),
  GlobalExerciseDef('Smith Machine Calf Raises', 'calves'),
  GlobalExerciseDef('Tibialis Raises', 'calves'),

  // Traps
  GlobalExerciseDef('Barbell Shrugs', 'back'),
  GlobalExerciseDef('Dumbbell Shrugs', 'back'),
  GlobalExerciseDef('Trap Bar Shrugs', 'back'),
  GlobalExerciseDef('Behind-the-back Shrugs', 'back'),
  GlobalExerciseDef('Scapular Pull-ups', 'back'),
  GlobalExerciseDef('Prone Trap Raises', 'back'),

  // Neck
  GlobalExerciseDef('Neck Flexion (Plate)', 'other'),
  GlobalExerciseDef('Neck Extension (Plate)', 'other'),
  GlobalExerciseDef('Neck Harness Work', 'other'),

  // Lower Back
  GlobalExerciseDef('Jefferson Curls', 'back'),

  // Hip Flexors
  GlobalExerciseDef('Psoas March', 'quads'),
  GlobalExerciseDef('Standing Cable Knee Raises', 'quads'),

  // Adductors
  GlobalExerciseDef('Adductor Machine', 'quads'),
  GlobalExerciseDef('Copenhagen Plank', 'quads'),

  // Abductors
  GlobalExerciseDef('Side-lying Leg Raises', 'glutes'),

  // Serratus Anterior
  GlobalExerciseDef('Serratus Push-ups', 'chest'),
  GlobalExerciseDef('Scapular Push-ups', 'chest'),

  // Rotator Cuff
  GlobalExerciseDef('External Rotation (Cable)', 'shoulders'),
  GlobalExerciseDef('External Rotation (Dumbbell)', 'shoulders'),
  GlobalExerciseDef('External Rotation (Banded)', 'shoulders'),
  GlobalExerciseDef('Scarecrows', 'shoulders'),

  // Conditioning
  GlobalExerciseDef('Power Clean', 'other'),
  GlobalExerciseDef('Hang Clean', 'other'),
  GlobalExerciseDef('Full Clean', 'other'),
  GlobalExerciseDef('Power Snatch', 'other'),
  GlobalExerciseDef('Thrusters', 'other'),
  GlobalExerciseDef('Turkish Get-ups', 'other'),
  GlobalExerciseDef('Sled Pushes', 'other'),
  GlobalExerciseDef('Sled Pulls', 'other'),
  GlobalExerciseDef('Sandbag Carries', 'other'),
  GlobalExerciseDef('Burpees', 'other'),
  GlobalExerciseDef('Wall Balls', 'other'),
  GlobalExerciseDef('Battle Ropes', 'other'),
];
